theme: jekyll-theme-slate

title: CaesarFramework Documentation
description: Framework documentation for creating Gladihoppers mods using CaesarFramework.

show_downloads: false

github:
  is_project_page: false
