theme: jekyll-theme-minimal

title: CaesarLibrary Documentation
description: Framework documentation for creating Gladihoppers mods using CaesarLibrary.

show_downloads: false

github:
  is_project_page: false
